# version: "3.0"

services:
  signing_app:
    build: .
    container_name: signing_app
    volumes:
      # Монтируем текущую директорию - ключ для разработки!
      - ./src:/app/src
    ports:
      - "8004:8000"
    environment:
      - PYTHONPATH=/app/lib/pycades

